# e2f3QC.R

# Erich S. Huang
# Sage Bionetworks
# Seattle, Washington
# erich.huang@sagebase.org

##########
# LOAD IN REQUIRED LIBRARIES
##########

require(mGenomics)
require(snm)
require(ggplot2)
require(Biobase)
require(synapseClient)
mplotEnt <- loadEntity('syn274067')
attach(mplotEnt)

# synapseLogin('username', 'password')

##########
# LOAD IN RAW DATA ENTITY FROM SCR
##########

e2f3Ent <- loadEntity('syn138509')
fits <- runWorkflow(e2f3Ent$cacheDir, workflow = 'snm')

##########
# PULL OUT THE EXPRESSION DATA
##########

exprDat <- exprs(fits$hgu133plus2[[1]])

# Create a treatment model matrix  (using the filename annotations)
treatment <- ifelse(grepl('E2F3', list.files(e2f3Ent$cacheDir)), "GFP", "E2F3")
X <- model.matrix(~ factor(treatment))
sigObj <- calcSig(exprDat, X)

##########
# GENERATE FIGURES ON DATA PRIOR TO SUPERVISED NORMALIZATION
##########

# custom function from generateFigures.R
varBarPlot <- pvalHistFig1(sigObj)

svdObj <- fs(exprDat)

# custom function from generateFigures.R
initPcPlots <- pcPlotsFig2(svdObj)

##########
# REGRESS OUT THE KNOWN EXPERIMENTAL PERTURBATION EFFECT (TREATMENT)
##########

# In order to better understand perturbation-independent latent structure in
# the data

propSSQ <- removeExpEffect(exprDat, X)

# Generate a figure
propSSQBarPlot <- propSSQFig3(propSSQ)

# Visual inspection of this figure suggests that the dependence kernel 
# should be set as rank 2
svaFit <- sva(exprDat, bio.var = X, n.sv = 2, num.iter = 30, diagnose = FALSE)

# Now, we'll visualize the estimated basis vectors 
subtractedPCPlot <- subSVDFig4(svaFit)

# The plots suggest that even with the experimental perturbation effect
# removed there is still latent structure that correlates with the 
# experimental treatment.

# One way to manages this is to estimate a dependence kernel from transcripts
# that are non-varying, as determined using the pi0 statistic to define a 
# significance cutoff. Basically, a dependence kernel is generated by taking
# an unweighted SVD of the data restricted to the first pi0 largest ranked 
# (by p values) transcripts.

nullNorm <- nullProbeNorm(sigObj, 4, e2f3Ent)

# Visualize the normalized data
normDF <- as.data.frame(cbind(1:19, u2$v))
colnames(normDF) <- c('samples', paste('normPrinComp', 1:19, sep = ''))

normFig1 <- ggplot(normDF, aes(samples, normPrinComp1)) +
  geom_point(aes(colour = factor(treatment))) +
  opts(title = 'Normalized Data: E2F3 Eigengene 1\n') +
  xlab('/nSamples') +
  ylab('Eigengene 1 Loading/n')

normFig2 <- ggplot(normDF, aes(samples, normPrinComp2)) +
  geom_point(aes(colour = factor(treatment))) +
  opts(title = 'Normalized Data: E2F3 Eigengene 2\n') +
  xlab('/nSamples') +
  ylab('Eigengene 2 Loading/n')

normFig3 <- ggplot(normDF, aes(samples, normPrinComp3)) +
  geom_point(aes(colour = factor(treatment))) +
  opts(title = 'Normalized Data: E2F3 Eigengene 3\n') +
  xlab('/nSamples') +
  ylab('Eigengene 3 Loading/n')

normFig4 <- ggplot(normDF, aes(samples, normPrinComp4)) +
  geom_point(aes(colour = factor(treatment))) +
  opts(title = 'Normalized Data: E2F3 Eigengene 4\n') +
  xlab('/nSamples') +
  ylab('Eigengene 4 Loading/n')

multiplot(normFig1, normFig2, normFig3, normFig4, cols = 2)

##########
# MAKE AN ESET OUT OF THE NORMALIZED DATA
##########

nE2F3Eset <- fits2$hgu133plus2$eset
tempPhen <- pData(nE2F3Eset)
tempPhen$treatment <- treatment
pData(nE2F3Eset) <- tempPhen

##########
# RUN BFRM IN THE SPARSE ANOVA MODE
##########

require(bfrm)

e2f3Anova <- bfrm(dat2, design = ifelse(treatment == 'E2F3', 1, 0))
mPPib <- e2f3Anova@results$mPostPib
topProbeLogical <- mPPib[ , 2] >= 0.99
topProbeInd <- grep("TRUE", topProbeLogical)

##########
# RUN BFRM IN THE FACTOR DISCOVERY MODE
##########

bCatEvolveFactor <- evolve(dat2, 
                           init = as.numeric(topProbeInd),
                           priorpsia = 2,
                           priorpsib = 0.005,
                           varThreshold = 0.85,
                           facThreshold = 0.95,
                           maxVarIter = 30,
                           minFacVars = 10,
                           maxFacVars = length(topProbeInd),
                           maxFacs = 50,
                           maxVars = length(topProbeInd)
                           )


##########
# SAVE ENTITIES
##########

# See syn346115 for result objects