# qcE2F3.R

# Erich S. Huang
# Sage Bionetworks
# Seattle, Washington
# erich.huang@sagebase.org

##########
# LOAD IN REQUIRED LIBRARIES
##########

require(mGenomics)
require(snm)
require(ggplot2)
require(Biobase)
require(synapseClient)

# synapseLogin('username', 'password')

##########
# SOURCE IN HELPER FUNCTIONS FROM GITHUB
##########

githubRepo <- 
  downloadRepo('Sage-Bionetworks/Cancer-Pathway-Sparse-Factor-Models')

source(paste(githubRepo@localPath, 
             '/helperFunctions/generateQCFigures.R', sep = ''))

source(paste(githubRepo@localPath, 
             '/helperFunctions/qcFunctions.R', sep = ''))

##########
# LOAD IN RAW DATA ENTITY FROM SCR
##########

e2f3Ent <- loadEntity('syn138509')
fits <- runWorkflow(e2f3Ent$cacheDir, workflow = 'snm')

##########
# PULL OUT THE EXPRESSION DATA
##########

exprDat <- exprs(fits$hgu133plus2[[1]])

# Create a treatment model matrix  (using the filename annotations)
treatment <- ifelse(grepl('E2F3', list.files(e2f3Ent$cacheDir)), "E2F3", "GFP")
X <- model.matrix(~ factor(treatment))
sigObj <- calcSig(exprDat, X)

##########
# GENERATE FIGURES ON DATA PRIOR TO SUPERVISED NORMALIZATION
##########

# custom function from generateFigures.R
varBarPlot <- qcFigureA(sigObj)

svdObj <- fs(exprDat)

# custom function from generateFigures.R
initPcPlots <- qcFigureB(svdObj)

##########
# REGRESS OUT THE KNOWN EXPERIMENTAL PERTURBATION EFFECT (TREATMENT)
##########

# In order to better understand perturbation-independent latent structure in
# the data

propSSQ <- removeExpEffect(exprDat, X)

# Generate a figure
propSSQBarPlot <- qcFigureC(propSSQ)

# Visual inspection of this figure suggests that the dependence kernel 
# should be set as rank 2
svaFit <- sva(exprDat, bio.var = X, n.sv = 2, num.iter = 30, diagnose = FALSE)

# Now, we'll visualize the estimated basis vectors 
subtractedPCPlot <- qcFigureD(svaFit)

# The plots suggest that even with the experimental perturbation effect
# removed there is still latent structure that correlates with the 
# experimental treatment.

# One way to manages this is to estimate a dependence kernel from transcripts
# that are non-varying, as determined using the pi0 statistic to define a 
# significance cutoff. Basically, a dependence kernel is generated by taking
# an unweighted SVD of the data restricted to the first pi0 largest ranked 
# (by p values) transcripts.
nullNorm <- nullProbeNorm(sigObj, 4, e2f3Ent)

# Visualize the normalized data
nullNormFig <- qcFigureE(nullNorm$uMatrix)

##########
# MAKE AN ESET OUT OF THE NORMALIZED DATA
##########

nE2F3Eset <- nullNorm$newFit$hgu133plus2$eset
tempPhen <- pData(nE2F3Eset)
tempPhen$treatment <- treatment
pData(nE2F3Eset) <- tempPhen

##########
# UPLOAD TO SYNAPSE
##########

sNormProjEnt <- loadEntity('syn1091237')
sNormProjEnt <- addObject(sNormProjEnt, nE2F3Eset)
sNormProjEnt$properties$parentId <- 'syn1091010'
annotations(sNormProjEnt, 'treatmentString') <- 'E2F3'
annotValue(sNormProjEnt, 'assayPlatform') <- 
  fits[[1]]$eset@annotation
sNormProjEnt <- storeEntity(sNormProjEnt)

