# qcEGFR.R

# Erich S. Huang
# Sage Bionetworks
# Seattle, Washington
# erich.huang@sagebase.org

##########
# LOAD IN REQUIRED LIBRARIES
##########

require(mGenomics)
require(snm)
require(ggplot2)
require(Biobase)
require(synapseClient)

# synapseLogin('username', 'password')

##########
# LOAD IN RAW DATA ENTITY FROM SCR
##########

egfrEnt <- loadEntity('syn138511')
fits <- runWorkflow(egfrEnt$cacheDir, workflow = 'snm')

##########
# PULL OUT THE EXPRESSION DATA
##########

exprDat <- exprs(fits[[1]][[1]])

# Create a treatment model matrix  (using the filename annotations)
treatment <- ifelse(grepl('wt', list.files(egfrEnt$cacheDir), 
                          ignore.case = TRUE), "EGFR", "GFP")
X <- model.matrix(~ factor(treatment))
sigObj <- calcSig(exprDat, X)

##########
# GENERATE FIGURES ON DATA PRIOR TO SUPERVISED NORMALIZATION
##########

# custom function from generateFigures.R
varBarPlot <- qcFigureA(sigObj)

svdObj <- fs(exprDat)

# custom function from generateFigures.R
initPcPlots <- qcFigureB(svdObj)

##########
# REGRESS OUT THE KNOWN EXPERIMENTAL PERTURBATION EFFECT (TREATMENT)
##########

# In order to better understand perturbation-independent latent structure in
# the data

propSSQ <- removeExpEffect(exprDat, X)

# Generate a figure
propSSQBarPlot <- qcFigureC(propSSQ)

# Visual inspection of this figure suggests that the dependence kernel 
# should be set as rank 2
svaFit <- sva(exprDat, bio.var = X, n.sv = 2, num.iter = 30, diagnose = FALSE)

# Now, we'll visualize the estimated basis vectors 
subtractedPCPlot <- qcFigureD(svaFit)

# The plots suggest that even with the experimental perturbation effect
# removed there is still latent structure that correlates with the 
# experimental treatment.

# One way to manages this is to estimate a dependence kernel from transcripts
# that are non-varying, as determined using the pi0 statistic to define a 
# significance cutoff. Basically, a dependence kernel is generated by taking
# an unweighted SVD of the data restricted to the first pi0 largest ranked 
# (by p values) transcripts.
nullNorm <- nullProbeNorm(sigObj, 2, egfrEnt)

# Visualize the normalized data
nullNormFig <- qcFigureE(nullNorm$uMatrix)

##########
# MAKE AN ESET OUT OF THE NORMALIZED DATA
##########

nEGFREset <- nullNorm$newFit[[1]][[1]]
tempPhen <- pData(nEGFREset)
tempPhen$treatment <- treatment
pData(nEGFREset) <- tempPhen

##########
# UPLOAD TO SYNAPSE
##########

sNormProjEnt <- getEntity('syn1091010')
sNormEGFREnt <- Data(list(name = "Supervised Normalized EGFR Perturbation Data",
                          parentId = propertyValue(sNormProjEnt, "id")))
annotValue(sNormEGFREnt, 'treatmentString') <- 'EGFR'
sNormEGFREnt <- addObject(sNormEGFREnt, nEGFREset)
sNormEGFREnt <- storeEntity(sNormEGFREnt)

